AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FileRead:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
