ARG ALPINE_VERSION
ARG UBI_VERSION

FROM alpine:${ALPINE_VERSION} AS extract

USER 1000:1000
ARG VERSION
RUN mkdir "/tmp/gpgpdump_${VERSION}" && \
	cd "/tmp/gpgpdump_${VERSION}" && \
	wget -O- "https://github.com/goark/gpgpdump/releases/download/v${VERSION}/gpgpdump_${VERSION}_Linux_64bit.tar.gz" | tar xzf -

FROM redhat/ubi8-micro:${UBI_VERSION}

ARG VERSION
COPY --from=extract --chown=root /tmp/gpgpdump_${VERSION} /opt/gpgpdump_${VERSION}
USER 1000:1000
ENV PATH $PATH:/opt/gpgpdump_$VERSION
